### ISSUE TITLE
placeholders={true} throws an error

### ISSUE THREAD

**Issue by DreySkee** [ideawork/iws-form-component#5]
Setting placeholders={true} on the Form component is throwing an error:
`TypeError: Cannot read property 'length' of undefined(…)      ContentStore.js:91`

Here's my form:

```
<Form action="/" errorMessages={false} placeholders={true}>
       <Datepicker id="arrival"    validate label="Arr"/>
       <Datepicker id="departure"  validate label="Dep"/>
       <Select     id="guests"     validate label="Number of guests"/>
       <Text       id="promo"      validate label="Promo Code"/>
</Form>
```

**Comment by SMLMRKHLMS** [comment]
@DreySkee I am trying to duplicate the issue; however, I am not seeing the error. Which browser are using and what project is the error taking place on?

**Comment by DreySkee** [comment]
@SMLMRKHLMS 
It's happening in Chrome.
Here's the project: https://bitbucket.org/ideawork/restoration
The form is in components/widgets/BookHome.js

**Comment by SMLMRKHLMS** [comment]
@DreySkee Ok. I will take a look at it to see if I can replicate the issue. Thanks.

**Comment by SMLMRKHLMS** [comment]
@DreySkee Found the issue and I pushed the change to the repo. Delete the from node_modules folder and reinstall. Let me know if you have any issues.

**Comment by DreySkee** [comment]
It's working. Thanks!
